//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_Library.Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Model_Library.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Account Management 的當地語系化字串。
        /// </summary>
        public static string Account_Management {
            get {
                return ResourceManager.GetString("Account_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Login Now 的當地語系化字串。
        /// </summary>
        public static string Already_have_account {
            get {
                return ResourceManager.GetString("Already_have_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Author / Organization Name 的當地語系化字串。
        /// </summary>
        public static string Author_or_Organization_Name {
            get {
                return ResourceManager.GetString("Author_or_Organization_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Belong to 的當地語系化字串。
        /// </summary>
        public static string Belong_to {
            get {
                return ResourceManager.GetString("Belong_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Build Dream Home 的當地語系化字串。
        /// </summary>
        public static string Build_dream_home {
            get {
                return ResourceManager.GetString("Build_dream_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cabinet 的當地語系化字串。
        /// </summary>
        public static string Cabinet {
            get {
                return ResourceManager.GetString("Cabinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Category 的當地語系化字串。
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 cm 的當地語系化字串。
        /// </summary>
        public static string centimeter {
            get {
                return ResourceManager.GetString("centimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Chair 的當地語系化字串。
        /// </summary>
        public static string Chair {
            get {
                return ResourceManager.GetString("Chair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Prepare to change Owner to 的當地語系化字串。
        /// </summary>
        public static string Change_Owner {
            get {
                return ResourceManager.GetString("Change_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Check Model 的當地語系化字串。
        /// </summary>
        public static string Check_Model {
            get {
                return ResourceManager.GetString("Check_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 choose permission to change 的當地語系化字串。
        /// </summary>
        public static string Choose_Permission {
            get {
                return ResourceManager.GetString("Choose_Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Comment 的當地語系化字串。
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Comment Area 的當地語系化字串。
        /// </summary>
        public static string Comment_Area {
            get {
                return ResourceManager.GetString("Comment_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Company/Organization 的當地語系化字串。
        /// </summary>
        public static string Company_or_Organization {
            get {
                return ResourceManager.GetString("Company_or_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Company Name 的當地語系化字串。
        /// </summary>
        public static string Company_Organization {
            get {
                return ResourceManager.GetString("Company_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Configuration 的當地語系化字串。
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Confirm Password 的當地語系化字串。
        /// </summary>
        public static string Confirm_Password {
            get {
                return ResourceManager.GetString("Confirm_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Contact Us 的當地語系化字串。
        /// </summary>
        public static string Contact_Us {
            get {
                return ResourceManager.GetString("Contact_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Country 的當地語系化字串。
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Create an account 的當地語系化字串。
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Create an account 的當地語系化字串。
        /// </summary>
        public static string Create_an_account {
            get {
                return ResourceManager.GetString("Create_an_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Created By 的當地語系化字串。
        /// </summary>
        public static string Created_By {
            get {
                return ResourceManager.GetString("Created_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Date of publishing 的當地語系化字串。
        /// </summary>
        public static string Created_Time {
            get {
                return ResourceManager.GetString("Created_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Date of publishing 的當地語系化字串。
        /// </summary>
        public static string Date_of_publishing {
            get {
                return ResourceManager.GetString("Date_of_publishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Depth 的當地語系化字串。
        /// </summary>
        public static string Depth {
            get {
                return ResourceManager.GetString("Depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Register Now 的當地語系化字串。
        /// </summary>
        public static string Dont_have_account {
            get {
                return ResourceManager.GetString("Dont_have_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Door 的當地語系化字串。
        /// </summary>
        public static string Door {
            get {
                return ResourceManager.GetString("Door", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Download 的當地語系化字串。
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Edit 的當地語系化字串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Email 的當地語系化字串。
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter your comment here 的當地語系化字串。
        /// </summary>
        public static string Enter_Comment {
            get {
                return ResourceManager.GetString("Enter_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter your company or organization name 的當地語系化字串。
        /// </summary>
        public static string Enter_Company_or_Organization {
            get {
                return ResourceManager.GetString("Enter_Company_or_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please confirm the password you entered 的當地語系化字串。
        /// </summary>
        public static string Enter_Confirm_Password {
            get {
                return ResourceManager.GetString("Enter_Confirm_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter your email 的當地語系化字串。
        /// </summary>
        public static string Enter_Email {
            get {
                return ResourceManager.GetString("Enter_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter your first name 的當地語系化字串。
        /// </summary>
        public static string Enter_First_Name {
            get {
                return ResourceManager.GetString("Enter_First_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter your last name 的當地語系化字串。
        /// </summary>
        public static string Enter_Last_Name {
            get {
                return ResourceManager.GetString("Enter_Last_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter your occupation 的當地語系化字串。
        /// </summary>
        public static string Enter_Occupation {
            get {
                return ResourceManager.GetString("Enter_Occupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter your password 的當地語系化字串。
        /// </summary>
        public static string Enter_Password {
            get {
                return ResourceManager.GetString("Enter_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter your username 的當地語系化字串。
        /// </summary>
        public static string Enter_Username {
            get {
                return ResourceManager.GetString("Enter_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter the verification code 的當地語系化字串。
        /// </summary>
        public static string Enter_Verification {
            get {
                return ResourceManager.GetString("Enter_Verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Facade / Curtain Wall 的當地語系化字串。
        /// </summary>
        public static string FacadeCurtainWall {
            get {
                return ResourceManager.GetString("FacadeCurtainWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 feet 的當地語系化字串。
        /// </summary>
        public static string feet {
            get {
                return ResourceManager.GetString("feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 File Type 的當地語系化字串。
        /// </summary>
        public static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 First Name 的當地語系化字串。
        /// </summary>
        public static string First_Name {
            get {
                return ResourceManager.GetString("First_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Full Name 的當地語系化字串。
        /// </summary>
        public static string Full_Name {
            get {
                return ResourceManager.GetString("Full_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Height 的當地語系化字串。
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 inch 的當地語系化字串。
        /// </summary>
        public static string inch {
            get {
                return ResourceManager.GetString("inch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Introduction 的當地語系化字串。
        /// </summary>
        public static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 km 的當地語系化字串。
        /// </summary>
        public static string kilometer {
            get {
                return ResourceManager.GetString("kilometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Lamp 的當地語系化字串。
        /// </summary>
        public static string Lamp {
            get {
                return ResourceManager.GetString("Lamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Last Name 的當地語系化字串。
        /// </summary>
        public static string Last_Name {
            get {
                return ResourceManager.GetString("Last_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Learn More 的當地語系化字串。
        /// </summary>
        public static string learn_more {
            get {
                return ResourceManager.GetString("learn_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Login 的當地語系化字串。
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 meter 的當地語系化字串。
        /// </summary>
        public static string meter {
            get {
                return ResourceManager.GetString("meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 mil 的當地語系化字串。
        /// </summary>
        public static string mile {
            get {
                return ResourceManager.GetString("mile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 mm 的當地語系化字串。
        /// </summary>
        public static string millimeter {
            get {
                return ResourceManager.GetString("millimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Model Information 的當地語系化字串。
        /// </summary>
        public static string Model_Information {
            get {
                return ResourceManager.GetString("Model_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Model Management 的當地語系化字串。
        /// </summary>
        public static string Model_Management {
            get {
                return ResourceManager.GetString("Model_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Model Name 的當地語系化字串。
        /// </summary>
        public static string Model_Name {
            get {
                return ResourceManager.GetString("Model_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 More 的當地語系化字串。
        /// </summary>
        public static string more {
            get {
                return ResourceManager.GetString("more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 More Detail 的當地語系化字串。
        /// </summary>
        public static string More_Detail {
            get {
                return ResourceManager.GetString("More_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 My Profile 的當地語系化字串。
        /// </summary>
        public static string My_Profile {
            get {
                return ResourceManager.GetString("My_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Object Name 的當地語系化字串。
        /// </summary>
        public static string Object_Name {
            get {
                return ResourceManager.GetString("Object_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Occupation 的當地語系化字串。
        /// </summary>
        public static string Occupation {
            get {
                return ResourceManager.GetString("Occupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Organization 的當地語系化字串。
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Our Products 的當地語系化字串。
        /// </summary>
        public static string Our_Products {
            get {
                return ResourceManager.GetString("Our_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Owner 的當地語系化字串。
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Password 的當地語系化字串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Permission 的當地語系化字串。
        /// </summary>
        public static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Personal 的當地語系化字串。
        /// </summary>
        public static string Personal {
            get {
                return ResourceManager.GetString("Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Product Accessories 的當地語系化字串。
        /// </summary>
        public static string Product_Accessories {
            get {
                return ResourceManager.GetString("Product_Accessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Product Structure 的當地語系化字串。
        /// </summary>
        public static string Product_Structure {
            get {
                return ResourceManager.GetString("Product_Structure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Profile 的當地語系化字串。
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Register 的當地語系化字串。
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Roof 的當地語系化字串。
        /// </summary>
        public static string Roof {
            get {
                return ResourceManager.GetString("Roof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Search 的當地語系化字串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Search by Category 的當地語系化字串。
        /// </summary>
        public static string Search_by_category {
            get {
                return ResourceManager.GetString("Search_by_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sign Out 的當地語系化字串。
        /// </summary>
        public static string Sign_Out {
            get {
                return ResourceManager.GetString("Sign_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sign Up 的當地語系化字串。
        /// </summary>
        public static string Sign_Up {
            get {
                return ResourceManager.GetString("Sign_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sofa 的當地語系化字串。
        /// </summary>
        public static string Sofa {
            get {
                return ResourceManager.GetString("Sofa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Software Specifications 的當地語系化字串。
        /// </summary>
        public static string Software_Specifications {
            get {
                return ResourceManager.GetString("Software_Specifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Specification 的當地語系化字串。
        /// </summary>
        public static string Specification {
            get {
                return ResourceManager.GetString("Specification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Table 的當地語系化字串。
        /// </summary>
        public static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Trending Products 的當地語系化字串。
        /// </summary>
        public static string Trending_products {
            get {
                return ResourceManager.GetString("Trending_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unit 的當地語系化字串。
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Upload 的當地語系化字串。
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Upload Image 的當地語系化字串。
        /// </summary>
        public static string Upload_Image {
            get {
                return ResourceManager.GetString("Upload_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Upload Model 的當地語系化字串。
        /// </summary>
        public static string Upload_Model {
            get {
                return ResourceManager.GetString("Upload_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Uploaded Model 的當地語系化字串。
        /// </summary>
        public static string Uploaded_Model {
            get {
                return ResourceManager.GetString("Uploaded_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Username 的當地語系化字串。
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Click to Change 的當地語系化字串。
        /// </summary>
        public static string V_Click {
            get {
                return ResourceManager.GetString("V_Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Verification Code 的當地語系化字串。
        /// </summary>
        public static string Verification_Code {
            get {
                return ResourceManager.GetString("Verification_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Version 的當地語系化字串。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Hello 的當地語系化字串。
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Width 的當地語系化字串。
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Window 的當地語系化字串。
        /// </summary>
        public static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 yard 的當地語系化字串。
        /// </summary>
        public static string yard {
            get {
                return ResourceManager.GetString("yard", resourceCulture);
            }
        }
    }
}
