//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model_Library.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Model_Library.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Management.
        /// </summary>
        public static string Account_Management {
            get {
                return ResourceManager.GetString("Account_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Now.
        /// </summary>
        public static string Already_have_account {
            get {
                return ResourceManager.GetString("Already_have_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author / Organization Name.
        /// </summary>
        public static string Author_or_Organization_Name {
            get {
                return ResourceManager.GetString("Author_or_Organization_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belong to.
        /// </summary>
        public static string Belong_to {
            get {
                return ResourceManager.GetString("Belong_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Dream Home.
        /// </summary>
        public static string Build_dream_home {
            get {
                return ResourceManager.GetString("Build_dream_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabinet.
        /// </summary>
        public static string Cabinet {
            get {
                return ResourceManager.GetString("Cabinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cm.
        /// </summary>
        public static string centimeter {
            get {
                return ResourceManager.GetString("centimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chair.
        /// </summary>
        public static string Chair {
            get {
                return ResourceManager.GetString("Chair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare to change Owner to.
        /// </summary>
        public static string Change_Owner {
            get {
                return ResourceManager.GetString("Change_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Model.
        /// </summary>
        public static string Check_Model {
            get {
                return ResourceManager.GetString("Check_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose permission to change.
        /// </summary>
        public static string Choose_Permission {
            get {
                return ResourceManager.GetString("Choose_Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment Area.
        /// </summary>
        public static string Comment_Area {
            get {
                return ResourceManager.GetString("Comment_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company/Organization.
        /// </summary>
        public static string Company_or_Organization {
            get {
                return ResourceManager.GetString("Company_or_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string Company_Organization {
            get {
                return ResourceManager.GetString("Company_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Confirm_Password {
            get {
                return ResourceManager.GetString("Confirm_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string Contact_Us {
            get {
                return ResourceManager.GetString("Contact_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account.
        /// </summary>
        public static string Create_an_account {
            get {
                return ResourceManager.GetString("Create_an_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string Created_By {
            get {
                return ResourceManager.GetString("Created_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of publishing.
        /// </summary>
        public static string Created_Time {
            get {
                return ResourceManager.GetString("Created_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of publishing.
        /// </summary>
        public static string Date_of_publishing {
            get {
                return ResourceManager.GetString("Date_of_publishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth.
        /// </summary>
        public static string Depth {
            get {
                return ResourceManager.GetString("Depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Now.
        /// </summary>
        public static string Dont_have_account {
            get {
                return ResourceManager.GetString("Dont_have_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door.
        /// </summary>
        public static string Door {
            get {
                return ResourceManager.GetString("Door", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your comment here.
        /// </summary>
        public static string Enter_Comment {
            get {
                return ResourceManager.GetString("Enter_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your company or organization name.
        /// </summary>
        public static string Enter_Company_or_Organization {
            get {
                return ResourceManager.GetString("Enter_Company_or_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm the password you entered.
        /// </summary>
        public static string Enter_Confirm_Password {
            get {
                return ResourceManager.GetString("Enter_Confirm_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email.
        /// </summary>
        public static string Enter_Email {
            get {
                return ResourceManager.GetString("Enter_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your first name.
        /// </summary>
        public static string Enter_First_Name {
            get {
                return ResourceManager.GetString("Enter_First_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your last name.
        /// </summary>
        public static string Enter_Last_Name {
            get {
                return ResourceManager.GetString("Enter_Last_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your occupation.
        /// </summary>
        public static string Enter_Occupation {
            get {
                return ResourceManager.GetString("Enter_Occupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password.
        /// </summary>
        public static string Enter_Password {
            get {
                return ResourceManager.GetString("Enter_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your username.
        /// </summary>
        public static string Enter_Username {
            get {
                return ResourceManager.GetString("Enter_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the verification code.
        /// </summary>
        public static string Enter_Verification {
            get {
                return ResourceManager.GetString("Enter_Verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FacadeCurtainWall.
        /// </summary>
        public static string FacadeCurtainWall {
            get {
                return ResourceManager.GetString("FacadeCurtainWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feet.
        /// </summary>
        public static string feet {
            get {
                return ResourceManager.GetString("feet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Type.
        /// </summary>
        public static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string First_Name {
            get {
                return ResourceManager.GetString("First_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string Full_Name {
            get {
                return ResourceManager.GetString("Full_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inch.
        /// </summary>
        public static string inch {
            get {
                return ResourceManager.GetString("inch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        public static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        public static string kilometer {
            get {
                return ResourceManager.GetString("kilometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lamp.
        /// </summary>
        public static string Lamp {
            get {
                return ResourceManager.GetString("Lamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Last_Name {
            get {
                return ResourceManager.GetString("Last_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More.
        /// </summary>
        public static string learn_more {
            get {
                return ResourceManager.GetString("learn_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meter.
        /// </summary>
        public static string meter {
            get {
                return ResourceManager.GetString("meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mil.
        /// </summary>
        public static string mile {
            get {
                return ResourceManager.GetString("mile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        public static string millimeter {
            get {
                return ResourceManager.GetString("millimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Information.
        /// </summary>
        public static string Model_Information {
            get {
                return ResourceManager.GetString("Model_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Management.
        /// </summary>
        public static string Model_Management {
            get {
                return ResourceManager.GetString("Model_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Name.
        /// </summary>
        public static string Model_Name {
            get {
                return ResourceManager.GetString("Model_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string more {
            get {
                return ResourceManager.GetString("more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Detail.
        /// </summary>
        public static string More_Detail {
            get {
                return ResourceManager.GetString("More_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string My_Profile {
            get {
                return ResourceManager.GetString("My_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Name.
        /// </summary>
        public static string Object_Name {
            get {
                return ResourceManager.GetString("Object_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupation.
        /// </summary>
        public static string Occupation {
            get {
                return ResourceManager.GetString("Occupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Products.
        /// </summary>
        public static string Our_Products {
            get {
                return ResourceManager.GetString("Our_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        public static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal.
        /// </summary>
        public static string Personal {
            get {
                return ResourceManager.GetString("Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Accessories.
        /// </summary>
        public static string Product_Accessories {
            get {
                return ResourceManager.GetString("Product_Accessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Structure.
        /// </summary>
        public static string Product_Structure {
            get {
                return ResourceManager.GetString("Product_Structure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roof.
        /// </summary>
        public static string Roof {
            get {
                return ResourceManager.GetString("Roof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Category.
        /// </summary>
        public static string Search_by_category {
            get {
                return ResourceManager.GetString("Search_by_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string Sign_Out {
            get {
                return ResourceManager.GetString("Sign_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string Sign_Up {
            get {
                return ResourceManager.GetString("Sign_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sofa.
        /// </summary>
        public static string Sofa {
            get {
                return ResourceManager.GetString("Sofa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Specifications.
        /// </summary>
        public static string Software_Specifications {
            get {
                return ResourceManager.GetString("Software_Specifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specification.
        /// </summary>
        public static string Specification {
            get {
                return ResourceManager.GetString("Specification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trending Products.
        /// </summary>
        public static string Trending_products {
            get {
                return ResourceManager.GetString("Trending_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Image.
        /// </summary>
        public static string Upload_Image {
            get {
                return ResourceManager.GetString("Upload_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Model.
        /// </summary>
        public static string Upload_Model {
            get {
                return ResourceManager.GetString("Upload_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded Model.
        /// </summary>
        public static string Uploaded_Model {
            get {
                return ResourceManager.GetString("Uploaded_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to Change.
        /// </summary>
        public static string V_Click {
            get {
                return ResourceManager.GetString("V_Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code.
        /// </summary>
        public static string Verification_Code {
            get {
                return ResourceManager.GetString("Verification_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        public static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yard.
        /// </summary>
        public static string yard {
            get {
                return ResourceManager.GetString("yard", resourceCulture);
            }
        }
    }
}
